"""tambah kolom image url ke categories

Revision ID: 05d3021b552a
Revises: aa9ef8f75313
Create Date: 2026-05-12 12:47:41.869568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d3021b552a'
down_revision: Union[str, Sequence[str], None] = 'aa9ef8f75313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
