"""seeder dan hapus icon di source

Revision ID: 17317ad032dc
Revises: 53dd95f8bc1f
Create Date: 2026-05-08 13:35:19.218688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = '17317ad032dc'
down_revision: Union[str, Sequence[str], None] = '53dd95f8bc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'icon')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###

    source_table = table('sources',
        column('id', sa.Integer),
        column('name', sa.String),
        column('type', sa.String)
    )

    source_type_table = table('source_type',
        column('id', sa.Integer),
        column('name', sa.String)
    )

    # 1. Seed Data SourceType
    op.bulk_insert(source_type_table, [
        {'id': 1, 'name': 'Internal'},
        {'id': 2, 'name': 'Eksternal'},
    ])

    # 2. Seed Data Source (Tanpa Icon)
    op.bulk_insert(source_table, [
        {'id': 1, 'name': 'Badan Pusat Statistik (BPS)', 'type': 'kementerian'},
        {'id': 2, 'name': 'Dinas Kesehatan', 'type': 'opd'},
        {'id': 3, 'name': 'Dinas Pendidikan', 'type': 'opd'},
        {'id': 4, 'name': 'Diskominfo', 'type': 'opd'},
        {'id': 5, 'name': 'Bappeda', 'type': 'opd'},
        {'id': 6, 'name': 'BRIDA', 'type': 'brida'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('sources', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
