"""add_source_id_to_users

Revision ID: 3c8dba19681c
Revises: c5995657278f
Create Date: 2026-06-09 11:36:00.544871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8dba19681c'
down_revision: Union[str, Sequence[str], None] = 'c5995657278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sources', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'source_id')
    # ### end Alembic commands ###
