"""add cloudinary fields

Revision ID: 7a739b4d9698
Revises: 17317ad032dc
Create Date: 2026-05-11 13:44:42.765174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a739b4d9698'
down_revision: Union[str, Sequence[str], None] = '17317ad032dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('template_url', sa.String(), nullable=True))
    op.add_column('datasets', sa.Column('image_url', sa.String(), nullable=True))
    # op.add_column('datasets', sa.Column('merged_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO categories (name, template_url) VALUES "
        "('Kependudukan', 'https://res.cloudinary.com/drcgddki1/image/upload/v1778482405/kategori_kependudukan-removebg-preview_k0nkgl.png'),"
        "('Kesehatan', 'https://res.cloudinary.com/drcgddki1/image/upload/v1778482406/kategori_kesehatan-removebg-preview_y4numn.png'),"
        "('Pendidikan', 'https://res.cloudinary.com/drcgddki1/image/upload/v1778482405/grok-image-8335bf9b-7580-4d59-b16e-c85a80e366dc-removebg-preview__2_-removebg-preview_1_edxbjq.png'),"
        "('Ekonomi', 'https://res.cloudinary.com/drcgddki1/image/upload/v1778482405/grok-image-975e1b97-dfc0-4056-8118-d4293f6fb069-removebg-preview__1_-removebg-preview_fb1ygq.png'),"
        "('Infrastruktur', 'https://res.cloudinary.com/drcgddki1/image/upload/v1778482405/grok-image-8a7e1a30-fff8-4965-8a01-1e3d318a6f20__1_-removebg-preview__1_-removebg-preview_ecfbwi.png')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('datasets', 'merged_image_url')
    op.drop_column('datasets', 'image_url')
    op.drop_column('categories', 'template_url')
    # ### end Alembic commands ###
