"""tambah  email responden

Revision ID: df4e62abe04e
Revises: 7a739b4d9698
Create Date: 2026-05-13 10:28:37.445937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4e62abe04e'
down_revision: Union[str, Sequence[str], None] = '7a739b4d9698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_responses', 'email')
    # ### end Alembic commands ###
